"""empty message

Revision ID: e0400f0d1450
Revises: 
Create Date: 2020-04-01 14:21:37.290295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0400f0d1450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_username', table_name='admins')
    op.drop_table('admins')
    op.add_column('product', sa.Column('image', sa.String(length=1000), nullable=True))
    op.add_column('product', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_image'), 'product', ['image'], unique=False)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.drop_index('ix_product_category', table_name='product')
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('admin', sa.VARCHAR(length=64), nullable=True))
    op.create_foreign_key(None, 'product', 'admin', ['admin'], ['id'])
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.create_index('ix_product_category', 'product', ['category'], unique=1)
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_image'), table_name='product')
    op.drop_column('product', 'price')
    op.drop_column('product', 'image')
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admins_username', 'admins', ['username'], unique=1)
    # ### end Alembic commands ###
